### ISSUE TITLE
For Annual Meeting: Manuscript 2: Account for F and survey start dates

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#47]
Account for differences in starting year of survey, catch, etc...

May also want ability to have holes in survey or catch data (e.g., survey every 2-3 years)

Basically need to define start dates for each data series, then adjust abundance value that is called (using a temporal adjustment to the y index) when calculating the given data series

This may require adding further breaks into the main code to account for periods prior to F....may be fairly complicated if different fleets have different time periods (i.e., not all Fs occuring simultaneously).

For surveys probably only need to adjust OBS survey values since survey does not impact pop dynamics (i.e., don't account for survey removals in abundance calcs).

This will be especially important for tagging calcs to match correct Fs, selectivity, etc..

**Comment by amyschueller** [comment]
Discussed at May meeting.  Reference #41 for additional information.  Decided to have the ability to set F=0 until the fishery started and to make sure the R wrapper picked up the correct data.

**Comment by jonathanderoba** [comment]
Jon coded the ability to set F=0 for a specified number of years at start of time series (issue #61).  Decided against holes in data or different start years by fleet at May 2017 meeting.
