### ISSUE TITLE
Manuscript 2: Tag-Integrated Assessment

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#48]
Make it

Ability to fit either area or population specific data (latter for natal homing scenarios where assume have catch composition information)

Make sure for tag data that only fit tag prop for ages/years that have releases (i.e., if survey_sel=0 for age-1 then don't fit age tag proportions)

Celebrate with a large amount of whisky

**Comment by KatelynBosley** [comment]
Uh...I think we might be there!! So I am CLOSING this issue.
