### ISSUE TITLE
For Annual Meeting: Manuscript 2: Alternate Movement Options

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#59]
Random Walk
Age-based (functional form)
Random
Devs (from average values...may need to implement logistic random deviates same as rec apportionment because dealing with a proportion that must be bound 0,1)
Alternate DD movement (base max T on input_T instead of input_residency, allow for random devs in max T)

**Comment by jonathanderoba** [comment]
Decided to just do DD, which is already coded.
