### ISSUE TITLE
For Annual Meeting: Manuscript 2: Alternate F Parametrizations

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#61]
Random Walk
Input Devs or F values (to imitate certain population trajectory)

**Comment by jonathanderoba** [comment]
I took a shot at random walk F and submitted my first pull request.  Success unknown.

**Comment by jonathanderoba** [comment]
Implemented an "F dunce cap" option where F=0 until you hit specified start year, then F increases from a specified min to a specified max half way through the time series, then decreases back to min at end of the time series.  Each region, fleet, pop, will have same F dunce cap shape but with LN errors to create some differences.
