### ISSUE TITLE
For Annual Meeting:  Manuscript 2: Alternate Recruit Parametrizations

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#62]
Temporal Autocorrelation (random walk in rec devs?)
Input devs (imitate population trajectory)

**Comment by brianlangseth** [comment]
I recently push some changes to the tag-integrated operating model for random walk recruitment deviations. Added a switch to the data file (requires lognormal recdev switch to be 1). This is my first push, so we'll see how it goes. 

Didn't do estimation model, but should be straightforward, only need to replace my new rec_devs_randwalk  variable with the old rec_devs variable in the objective function.
