### ISSUE TITLE
Reassigning an array

### ISSUE THREAD

**Issue by GreatDana** [KatelynBosley/SPASAM#78]
For langseth... this is an example of a for loop you need to change the order of an array, and then bring it back if needed , this example is moving the fish in the natage matrix, and then reassiging them to the natage matrix. 

 for(j=1;j<=10;j++){ 
     for (k=1;k<=nareas;k++) {
     AMnatage_f(i,k,j)=natage_f(k,i,j);
     AMnatage_m(i,k,j)=natage_m(k,i,j); }
     AMnatage_f(i)=trans(phi(2))*AMnatage_f(i) ;
     AMnatage_m(i)=trans(phi(2))*AMnatage_m(i) ; 
     for (k=1;k<=nareas;k++) {
     natage_f(k,i,j)=AMnatage_f(i,k,j);
     natage_m(k,i,j)=AMnatage_m(i,k,j); }}

**Comment by brianlangseth** [comment]
Added to thread in issue #41 and closed here.
