### ISSUE TITLE
Inf or ind values for 4 variables in report file of Tag-Integrated Model

### ISSUE THREAD

**Issue by brianlangseth** [KatelynBosley/SPASAM#90]
Current Tag-Integrated Model runs ok, but when trying to access the report out file in R using out=PBSmodelling::readList("filename.rep")
I run into unexpected errors with 6 variables. 

tag_prop_final
OBS_tag_prop_final
harvest_rate_region_bio_overlap
harvest_rate_population_bio_overlap
depletion_region_overlap
depletion_population_overlap

The first two are issues with reading 5d arrays, so can comment out (lines 5136-5139). However, the values for the other 4 variables (which are 3d or 4d arrays) read #inf or #ind.  I guessing it is a calculation issue. Need to check.

**Comment by KatelynBosley** [comment]
I updated the dat file so the calculations do not return nan or in values. I also commented out the 5-d arrays. Not sure that we will need them. Things are working smoothly now.
